name: kpop
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.6
  firebase_core: ^0.4.0+8
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+2
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  flutter_webview_plugin: ^0.3.11
  transparent_image: ^1.0.0
  flutter_localizations :
    sdk : flutter
  flutter_cupertino_localizations : ^1.0.1   
  firebase_messaging: ^5.1.3
  youtube_player_flutter: ^6.1.1
  firebase_admob: ^0.9.3+2
  share: ^0.6.2+1
  flutter_launcher_icons: ^0.7.2+1
  provider: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/appicon.png"
  android: true
  ios: true



flutter:

  uses-material-design: true
  
  assets:
    - images/
    - language/
    - singer/
    
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf